**Experiment 1: TensorFlow Installation & Version Check**

Importing the tensorflow library and printing its version ->

In [29]:
pip install tensorflow

In [9]:
import tensorflow as tf
print(tf.__version__)

2.19.0


**Experiment 2: Creating and Printing Tensors**

Creating A Tensor ->

In [3]:
scalar = tf.constant(10)

Create a scalar tensor ->

In [11]:
vector = tf.constant([1, 2, 3, 4])

Create a vector tensor ->

In [8]:

matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6]])

Display all tensors ->

In [7]:

print("Scalar Tensor:")
print(scalar)

print("\nVector Tensor:")
print(vector)

print("\nMatrix Tensor:")
print(matrix)


Scalar Tensor:
tf.Tensor(10, shape=(), dtype=int32)

Vector Tensor:
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)

Matrix Tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


Creating Different tytpes of Tensors ->

In [16]:
scalar = tf.constant(10) # Creating a scalar tensor

vector = tf.constant([1, 2, 3, 4]) # Creating a vector tensor

matrix = tf.constant([[1, 2, 3],  # Creating a matrix tensor
                      [4, 5, 6]])

tensor_3d = tf.constant([
    [[1, 2, 3],            # Creating a 3-D tensor
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print("Scalar Tensor:")
print(scalar)

print("\nVector Tensor:")
print(vector)

print("\nMatrix Tensor:")
print(matrix)

print("\n3-D Tensor:")
print(tensor_3d)


Scalar Tensor:
tf.Tensor(10, shape=(), dtype=int32)

Vector Tensor:
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)

Matrix Tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

3-D Tensor:
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


Performing some basic operations on the tensors ->

In [18]:

a = tf.constant([1, 2, 3])   # Create tensors
b = tf.constant([4, 5, 6])


add = tf.add(a, b)  # Addition


sub = tf.subtract(b, a)   # Subtraction


mul = tf.multiply(a, b)   # Element-wise multiplication


div = tf.divide(b, a) # Division



m1 = tf.constant([[1, 2],
                  [3, 4]])
m2 = tf.constant([[5, 6],
                  [7, 8]])
matmul = tf.matmul(m1, m2)  # Matrix multiplication


shape = a.shape     # Shape and Rank
rank = tf.rank(a)


sum_val = tf.reduce_sum(a)  # Reduction operations
mean_val = tf.reduce_mean(a)


print("Tensor a:", a)

print("\nTensor b:", b)

print("\nAddition:", add)

print("\nSubtraction:", sub)

print("\nMultiplication:", mul)

print("\nDivision:", div)

print("\nMatrix Multiplication:\n", matmul)

print("\nShape of tensor a:", shape)

print("\nRank of tensor a:", rank)

print("\nSum of elements in tensor a:", sum_val)

print("\nMean of elements in tensor a:", mean_val)


Tensor a: tf.Tensor([1 2 3], shape=(3,), dtype=int32)

Tensor b: tf.Tensor([4 5 6], shape=(3,), dtype=int32)

Addition: tf.Tensor([5 7 9], shape=(3,), dtype=int32)

Subtraction: tf.Tensor([3 3 3], shape=(3,), dtype=int32)

Multiplication: tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)

Division: tf.Tensor([4.  2.5 2. ], shape=(3,), dtype=float64)

Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)

Shape of tensor a: (3,)

Rank of tensor a: tf.Tensor(1, shape=(), dtype=int32)

Sum of elements in tensor a: tf.Tensor(6, shape=(), dtype=int32)

Mean of elements in tensor a: tf.Tensor(2, shape=(), dtype=int32)


**Experiment 3: Basic Tensor Operations :**

 SCALAR OPERATIONS

In [20]:
s1 = tf.constant(4)
s2 = tf.constant(2)

print("----- SCALAR OPERATIONS -----")
print("\nAddition:", tf.add(s1, s2))
print("\nSubtraction:", tf.subtract(s1, s2))
print("\nMultiplication:", tf.multiply(s1, s2))
print("\nDivision:", tf.divide(s1, s2))
print("\nPower:", tf.pow(s1, s2))

----- SCALAR OPERATIONS -----

Addition: tf.Tensor(6, shape=(), dtype=int32)

Subtraction: tf.Tensor(2, shape=(), dtype=int32)

Multiplication: tf.Tensor(8, shape=(), dtype=int32)

Division: tf.Tensor(2.0, shape=(), dtype=float64)

Power: tf.Tensor(16, shape=(), dtype=int32)


VECTOR OPERATIONS

In [21]:
v1 = tf.constant([1, 2, 3])
v2 = tf.constant([4, 5, 6])

print("\n----- VECTOR OPERATIONS -----")
print("Addition:", tf.add(v1, v2))
print("Subtraction:", tf.subtract(v2, v1))
print("Multiplication:", tf.multiply(v1, v2))
print("Division:", tf.divide(v2, v1))
print("Power:", tf.pow(v1, 2))


----- VECTOR OPERATIONS -----
Addition: tf.Tensor([5 7 9], shape=(3,), dtype=int32)
Subtraction: tf.Tensor([3 3 3], shape=(3,), dtype=int32)
Multiplication: tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
Division: tf.Tensor([4.  2.5 2. ], shape=(3,), dtype=float64)
Power: tf.Tensor([1 4 9], shape=(3,), dtype=int32)


2-D MATRIX OPERATIONS

In [22]:
m1 = tf.constant([[1, 2],
                  [3, 4]])

m2 = tf.constant([[5, 6],
                  [7, 8]])

print("\n----- 2-D MATRIX OPERATIONS -----")
print("Addition:\n", tf.add(m1, m2))
print("Subtraction:\n", tf.subtract(m2, m1))
print("Multiplication:\n", tf.multiply(m1, m2))   # element-wise
print("Division:\n", tf.divide(m2, m1))
print("Power:\n", tf.pow(m1, 2))


----- 2-D MATRIX OPERATIONS -----
Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Subtraction:
 tf.Tensor(
[[4 4]
 [4 4]], shape=(2, 2), dtype=int32)
Multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
Division:
 tf.Tensor(
[[5.         3.        ]
 [2.33333333 2.        ]], shape=(2, 2), dtype=float64)
Power:
 tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)


**Experiment 4: Data Types and Shape of Tensors**

In [27]:
scalar = tf.constant(10)

print("\nTensor:", scalar)
print("\nData Type:", scalar.dtype)
print("\nShape:", scalar.shape)
print("\nRank:", tf.rank(scalar))


vector = tf.constant([1, 2, 3, 4])

print("\nTensor:", vector)
print("\nData Type:", vector.dtype)
print("\nShape:", vector.shape)
print("\nRank:", tf.rank(vector))



matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6]])


print("\nTensor:\n", matrix)
print("\nData Type:", matrix.dtype)
print("\nShape:", matrix.shape)
print("\nRank:", tf.rank(matrix))



Tensor: tf.Tensor(10, shape=(), dtype=int32)

Data Type: <dtype: 'int32'>

Shape: ()

Rank: tf.Tensor(0, shape=(), dtype=int32)

Tensor: tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)

Data Type: <dtype: 'int32'>

Shape: (4,)

Rank: tf.Tensor(1, shape=(), dtype=int32)

Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Data Type: <dtype: 'int32'>

Shape: (2, 3)

Rank: tf.Tensor(2, shape=(), dtype=int32)


**Experiment 5: Converting NumPy Arrays to Tensors**

In [30]:
import numpy as np

numpy_scalar = np.array(5)
tensor_scalar = tf.convert_to_tensor(numpy_scalar)

print("----- SCALAR -----")
print("\nNumPy Scalar:", numpy_scalar)
print("\nTensor Scalar:", tensor_scalar)



numpy_vector = np.array([1, 2, 3, 4])
tensor_vector = tf.convert_to_tensor(numpy_vector)


print("\nNumPy Vector:", numpy_vector)
print("\nTensor Vector:", tensor_vector)



numpy_matrix = np.array([[1, 2, 3],
                         [4, 5, 6]])
tensor_matrix = tf.convert_to_tensor(numpy_matrix)


print("\nNumPy Matrix:")
print(numpy_matrix)
print("\nTensor Matrix:")
print(tensor_matrix)


----- SCALAR -----

NumPy Scalar: 5

Tensor Scalar: tf.Tensor(5, shape=(), dtype=int64)

NumPy Vector: [1 2 3 4]

Tensor Vector: tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)

NumPy Matrix:
[[1 2 3]
 [4 5 6]]

Tensor Matrix:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)
